question_autor_questao:
    type: rest
    resource: QuestionBundle\Controller\AutorDaQuestaoController
    name_prefix:  aspe_

question_opcao:
    type: rest
    resource: QuestionBundle\Controller\OpcaoController
    name_prefix:  aspe_

question_questao:
    type: rest
    resource: QuestionBundle\Controller\QuestaoController
    name_prefix:  aspe_
