# src/Acme/BlogBundle/Resources/config/validation.yml
#QuestionBundle\Entity\Page:
#    properties: 
#        id:
#            - 'Null': ~
#        title:
#            - NotBlank: ~
#            - NotNull: ~
#            - Length:
#                min: 2
#                max: 50
#                minMessage: "Your title must be at least {{ limit }} characters length"
#                maxMessage: "Your title name cannot be longer than {{ limit }} characters length"
#QuestionBundle\Entity\Usuario:
#    properties:
#        nome:
#            - NotBlank: ~
#            - NotNull: ~